/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jFResgistrarse.java
 *
 * Created on 08/08/2010, 10:14:12 PM
 */

package Interface;

/**
 *
 * @author Robert
 */
public class VentanaResgistro extends javax.swing.JFrame {

    /** Creates new form jFResgistrarse */
    public VentanaResgistro() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTituloRegistroUsuario = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jLCedula = new javax.swing.JLabel();
        jLFechaNaci = new javax.swing.JLabel();
        jLNickName = new javax.swing.JLabel();
        jLPassword = new javax.swing.JLabel();
        jLConfirmaPassword = new javax.swing.JLabel();
        jLAvatar = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jTFApellido = new javax.swing.JTextField();
        jTFCedula = new javax.swing.JTextField();
        jTFFevhaNaci = new javax.swing.JTextField();
        jTFNickName = new javax.swing.JTextField();
        jPasswordFieldConfirma = new javax.swing.JPasswordField();
        jPasswordField = new javax.swing.JPasswordField();
        jTFAvatar = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTituloRegistroUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLTituloRegistroUsuario.setText(" Registro Usuario");

        jLNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLNombre.setText("Nombre:");

        jLApellido.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLApellido.setText("Apellido:");

        jLCedula.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLCedula.setText("C.I:");

        jLFechaNaci.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLFechaNaci.setText("Fecha Nacimiento:");

        jLNickName.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLNickName.setText("NickName:");

        jLPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLPassword.setText("Password:");

        jLConfirmaPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLConfirmaPassword.setText("Confirmar Pasword:");

        jLAvatar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLAvatar.setText("Avatar:");

        jTFNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });

        jTFApellido.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jTFCedula.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jTFFevhaNaci.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jTFNickName.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jPasswordFieldConfirma.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jPasswordFieldConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldConfirmaActionPerformed(evt);
            }
        });

        jPasswordField.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jTFAvatar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jBGuardar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jBGuardar.setText("Guardar");

        jBAtras.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jBAtras.setText("<< Atras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLTituloRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLCedula)
                            .addComponent(jLApellido)
                            .addComponent(jLNombre)
                            .addComponent(jLFechaNaci)
                            .addComponent(jLNickName)
                            .addComponent(jLPassword)
                            .addComponent(jLAvatar)
                            .addComponent(jLConfirmaPassword))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(jTFCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(jTFNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(jTFFevhaNaci, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                            .addComponent(jTFNickName, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jBAtras))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLTituloRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApellido)
                    .addComponent(jTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCedula)
                    .addComponent(jTFCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFechaNaci)
                    .addComponent(jTFFevhaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNickName)
                    .addComponent(jTFNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPassword)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLConfirmaPassword)
                    .addComponent(jPasswordFieldConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAvatar)
                    .addComponent(jTFAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAtras)
                    .addComponent(jBGuardar))
                .addGap(33, 33, 33))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-370)/2, (screenSize.height-460)/2, 370, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jPasswordFieldConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldConfirmaActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaResgistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLAvatar;
    private javax.swing.JLabel jLCedula;
    private javax.swing.JLabel jLConfirmaPassword;
    private javax.swing.JLabel jLFechaNaci;
    private javax.swing.JLabel jLNickName;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPassword;
    private javax.swing.JLabel jLTituloRegistroUsuario;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordFieldConfirma;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFAvatar;
    private javax.swing.JTextField jTFCedula;
    private javax.swing.JTextField jTFFevhaNaci;
    private javax.swing.JTextField jTFNickName;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables

}
