/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jFResgistrarse.java
 *
 * Created on 08/08/2010, 10:14:12 PM
 */

package Interface;

import Logica.Comunicacion;

/**
 *
 * @author Robert
 */
public class VentanaRegistro extends javax.swing.JFrame {

    /** Creates new form jFResgistrarse */
    public VentanaRegistro() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLTituloRegistroUsuario = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jLCedula = new javax.swing.JLabel();
        jLFechaNaci = new javax.swing.JLabel();
        jLNickName = new javax.swing.JLabel();
        jLPassword = new javax.swing.JLabel();
        jLConfirmaPassword = new javax.swing.JLabel();
        jLAvatar = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jTFApellido = new javax.swing.JTextField();
        jTFCedula = new javax.swing.JTextField();
        jTFNickName = new javax.swing.JTextField();
        jTPFConfirmaPassword = new javax.swing.JPasswordField();
        jTPFPassword = new javax.swing.JPasswordField();
        jBGuardar = new javax.swing.JButton();
        jBAtras = new javax.swing.JButton();
        jLImagenFumador = new javax.swing.JLabel();
        jLImageHomero = new javax.swing.JLabel();
        jLImagenMujer = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLImagenRubia = new javax.swing.JLabel();
        jLImagenSherk = new javax.swing.JLabel();
        jLImagenStewie = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jDCFechaNaci = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro De Usuario");
        setName("VentanaRegistro"); // NOI18N

        jLTituloRegistroUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 18));
        jLTituloRegistroUsuario.setText(" Registro Usuario");

        jLNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLNombre.setText("Nombre:");

        jLApellido.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLApellido.setText("Apellido:");

        jLCedula.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLCedula.setText("C.I:");

        jLFechaNaci.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLFechaNaci.setText("Fecha Nacimiento:");

        jLNickName.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLNickName.setText("NickName:");

        jLPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLPassword.setText("Password:");

        jLConfirmaPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLConfirmaPassword.setText("Confirmar Pasword:");

        jLAvatar.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLAvatar.setText("Avatar:");

        jTFNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });

        jTFApellido.setFont(new java.awt.Font("Comic Sans MS", 0, 11));

        jTFCedula.setFont(new java.awt.Font("Comic Sans MS", 0, 11));

        jTFNickName.setFont(new java.awt.Font("Comic Sans MS", 0, 11));

        jTPFConfirmaPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jTPFConfirmaPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPFConfirmaPasswordActionPerformed(evt);
            }
        });

        jTPFPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jTPFPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPFPasswordActionPerformed(evt);
            }
        });

        jBGuardar.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBAtras.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jBAtras.setText("<< Atras");
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });

        jLImagenFumador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/JugadorFumon.JPEG.jpg"))); // NOI18N

        jLImageHomero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/JugadorHomero.JPEG.jpg"))); // NOI18N

        jLImagenMujer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/JugadorPlayera.JPEG.jpg"))); // NOI18N

        jLImagenRubia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/JugadorRubia.jpg.jpg"))); // NOI18N

        jLImagenSherk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/JugadorShrek.jpg.jpg"))); // NOI18N

        jLImagenStewie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/JugadorStewie.jpg.jpg"))); // NOI18N

        jDCFechaNaci.setName("jDCFechaNaci"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLNombre)
                            .addComponent(jLApellido)
                            .addComponent(jLCedula)
                            .addComponent(jLFechaNaci)
                            .addComponent(jLNickName)
                            .addComponent(jLPassword))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDCFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTFNickName, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addComponent(jLTituloRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addComponent(jTFApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addComponent(jTFCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addComponent(jTPFPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLImagenStewie)
                                        .addComponent(jLImageHomero, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRadioButton9)
                                        .addComponent(jRadioButton1)
                                        .addComponent(jBAtras))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jRadioButton3)
                                            .addComponent(jLImagenMujer))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jRadioButton8)
                                            .addComponent(jLImagenRubia, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLAvatar)
                            .addComponent(jLConfirmaPassword))
                        .addGap(18, 18, 18)
                        .addComponent(jTPFConfirmaPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLImagenSherk)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jRadioButton2)
                                .addComponent(jLImagenFumador))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jRadioButton7)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNombre)
                            .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLApellido)
                            .addComponent(jTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCedula)
                            .addComponent(jTFCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLTituloRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDCFechaNaci, 0, 0, Short.MAX_VALUE)
                    .addComponent(jLFechaNaci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNickName)
                    .addComponent(jTFNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPassword)
                    .addComponent(jTPFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLConfirmaPassword)
                    .addComponent(jTPFConfirmaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLAvatar)
                            .addComponent(jLImageHomero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton1)))
                    .addComponent(jLImagenMujer)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLImagenFumador, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLImagenStewie, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLImagenSherk)
                        .addComponent(jLImagenRubia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton8))
                        .addGap(96, 96, 96))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBAtras)
                            .addComponent(jBGuardar))
                        .addContainerGap())))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-469)/2, (screenSize.height-675)/2, 469, 675);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jTPFConfirmaPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPFConfirmaPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPFConfirmaPasswordActionPerformed

    private void jTPFPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPFPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPFPasswordActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
       Ventana_Crear_Cargar_Partida verVentana = new Ventana_Crear_Cargar_Partida();
       verVentana.setVisible(true);
       Comunicacion.obtenerDatos(jTFNombre, jTFApellido, jTFCedula, jDCFechaNaci, jTFNickName, jTPFPassword, jLAvatar);
       System.out.println(jDCFechaNaci.getDate().toString());
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
       VentanaInicio verVentana = new VentanaInicio();
       verVentana.setVisible(true);

    }//GEN-LAST:event_jBAtrasActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBGuardar;
    private com.toedter.calendar.JDateChooser jDCFechaNaci;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLAvatar;
    private javax.swing.JLabel jLCedula;
    private javax.swing.JLabel jLConfirmaPassword;
    private javax.swing.JLabel jLFechaNaci;
    private javax.swing.JLabel jLImageHomero;
    private javax.swing.JLabel jLImagenFumador;
    private javax.swing.JLabel jLImagenMujer;
    private javax.swing.JLabel jLImagenRubia;
    private javax.swing.JLabel jLImagenSherk;
    private javax.swing.JLabel jLImagenStewie;
    private javax.swing.JLabel jLNickName;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPassword;
    private javax.swing.JLabel jLTituloRegistroUsuario;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFCedula;
    private javax.swing.JTextField jTFNickName;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JPasswordField jTPFConfirmaPassword;
    private javax.swing.JPasswordField jTPFPassword;
    // End of variables declaration//GEN-END:variables

}
