/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Inicio.java
 *
 * Created on 08-ago-2010, 15:38:23
 */

package Interface;

/**
 *
 * @author Robert
 */
public class VentnaInicio extends javax.swing.JFrame {

    /** Creates new form Inicio */
    public VentnaInicio() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo_iDomino = new javax.swing.JLabel();
        jTFNickName = new javax.swing.JTextField();
        jTFPassword = new javax.swing.JTextField();
        jLNickName = new javax.swing.JLabel();
        jLPassword = new javax.swing.JLabel();
        jBRegistrarse = new javax.swing.JButton();
        jBEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO iDOMINO");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        setLocationByPlatform(true);
        setName("jFVentanaInicio"); // NOI18N
        setResizable(false);

        jLTitulo_iDomino.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        jLTitulo_iDomino.setText("   iDomino");
        jLTitulo_iDomino.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTFNickName.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jTFPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jLNickName.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLNickName.setText("Nickname:");

        jLPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLPassword.setText("PassWord:");

        jBRegistrarse.setBackground(new java.awt.Color(204, 204, 204));
        jBRegistrarse.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jBRegistrarse.setActionCommand("jBRegistrarse");
        jBRegistrarse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBRegistrarse.setLabel("Registrarse");

        jBEntrar.setBackground(new java.awt.Color(204, 204, 204));
        jBEntrar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jBEntrar.setActionCommand("jBEntrar");
        jBEntrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBEntrar.setLabel("Entrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLNickName)
                            .addComponent(jLPassword))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTFNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLTitulo_iDomino, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jBRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jBEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo_iDomino, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNickName)
                    .addComponent(jTFNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPassword)
                    .addComponent(jTFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRegistrarse)
                    .addComponent(jBEntrar))
                .addGap(29, 29, 29))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-295)/2, (screenSize.height-266)/2, 295, 266);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentnaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEntrar;
    private javax.swing.JButton jBRegistrarse;
    private javax.swing.JLabel jLNickName;
    private javax.swing.JLabel jLPassword;
    private javax.swing.JLabel jLTitulo_iDomino;
    private javax.swing.JTextField jTFNickName;
    private javax.swing.JTextField jTFPassword;
    // End of variables declaration//GEN-END:variables

}
