/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaCrearPartida.java
 *
 * Created on 12/08/2010, 04:48:39 PM
 */

package Cliente.presentacion;

/**
 *
 * @author Diego
 */
public class VentanaCrearPartida extends javax.swing.JFrame {

    /** Creates new form VentanaCrearPartida */
    public VentanaCrearPartida() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLNickJugador = new javax.swing.JLabel();
        jLPiezas = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CREAR PARTIDA");
        setName("jFCrearPartida"); // NOI18N

        jLNickJugador.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLNickJugador.setText("Jugado:::");

        jLPiezas.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLPiezas.setText("PIEZAS:::");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNickJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLNickJugador)
                .addGap(41, 41, 41)
                .addComponent(jLPiezas)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-336)/2, 416, 336);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCrearPartida().setVisible(true);
           String nickJugador;
             //jLNickJugador.setText(jLabel1.getText());

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLNickJugador;
    private javax.swing.JLabel jLPiezas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
