/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jFResgistrarse.java
 *
 * Created on 08/08/2010, 10:14:12 PM
 */

package Cliente.presentacion;

//import Interface.Ventana_Crear_Cargar_Partida;
import Servidor.logica.Comunicacion;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import javax.swing.*;
import ve.edu.ucab.cliente.ClienteSocket;

/**
 *
 * @author Robert
 */
public class VentanaRegistro extends javax.swing.JFrame {

    /** Creates new form jFResgistrarse */
    public VentanaRegistro() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLTituloRegistroUsuario = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jLFechaNaci = new javax.swing.JLabel();
        jLNickName = new javax.swing.JLabel();
        jLPassword = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jTFApellido = new javax.swing.JTextField();
        jTFNickName = new javax.swing.JTextField();
        jTPFPassword = new javax.swing.JPasswordField();
        jBGuardar = new javax.swing.JButton();
        jBAtras = new javax.swing.JButton();
        jRBJugadorHomero = new javax.swing.JRadioButton();
        jRBJugadorFumon = new javax.swing.JRadioButton();
        jRBJugadorPlayera = new javax.swing.JRadioButton();
        jRBJugadorShrek = new javax.swing.JRadioButton();
        jRBJugadorRubia = new javax.swing.JRadioButton();
        jRBJugadorStewie = new javax.swing.JRadioButton();
        jDCFechaNaci = new com.toedter.calendar.JDateChooser();
        jLAvatar = new javax.swing.JLabel();
        jLJugadorHomero = new javax.swing.JLabel();
        jLJugadorPlayera = new javax.swing.JLabel();
        jLJugadorFumon = new javax.swing.JLabel();
        jLStewie = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLShrek = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro De Usuario");
        setName("VentanaRegistro"); // NOI18N

        jLTituloRegistroUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 18));
        jLTituloRegistroUsuario.setText(" Registro Usuario");

        jLNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLNombre.setText("Nombre:");

        jLApellido.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLApellido.setText("Apellido:");

        jLFechaNaci.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLFechaNaci.setText("Fecha Nacimiento:");

        jLNickName.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLNickName.setText("NickName:");

        jLPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLPassword.setText("Password:");

        jTFNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });

        jTFApellido.setFont(new java.awt.Font("Comic Sans MS", 0, 11));

        jTFNickName.setFont(new java.awt.Font("Comic Sans MS", 0, 11));

        jTPFPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jTPFPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPFPasswordActionPerformed(evt);
            }
        });

        jBGuardar.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBAtras.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jBAtras.setText("<< Atras");
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBJugadorHomero);
        jRBJugadorHomero.setSelected(true);

        buttonGroup1.add(jRBJugadorFumon);

        buttonGroup1.add(jRBJugadorPlayera);
        jRBJugadorPlayera.setVerifyInputWhenFocusTarget(false);

        buttonGroup1.add(jRBJugadorShrek);

        buttonGroup1.add(jRBJugadorRubia);

        buttonGroup1.add(jRBJugadorStewie);
        jRBJugadorStewie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBJugadorStewieActionPerformed(evt);
            }
        });

        jDCFechaNaci.setDateFormatString("dd/MM/yy");
        jDCFechaNaci.setName("jDCFechaNaci"); // NOI18N

        jLAvatar.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLAvatar.setText("Avatar");

        jLJugadorHomero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cliente/presentacion/JugadorHomero.jpg"))); // NOI18N

        jLJugadorPlayera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cliente/presentacion/JugadorPlayera.jpg"))); // NOI18N

        jLJugadorFumon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cliente/presentacion/JugadorFumon.jpg"))); // NOI18N

        jLStewie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cliente/presentacion/JugadorStewie.jpg"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cliente/presentacion/JugadorRubia.jpg"))); // NOI18N

        jLShrek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cliente/presentacion/JugadorShrek.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLTituloRegistroUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addGap(165, 165, 165))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLFechaNaci, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLNickName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLAvatar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBAtras)
                        .addGap(80, 80, 80)
                        .addComponent(jBGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLJugadorHomero, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRBJugadorHomero))
                            .addComponent(jLStewie)
                            .addComponent(jRBJugadorStewie))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLJugadorPlayera)
                            .addComponent(jRBJugadorPlayera)
                            .addComponent(jRBJugadorRubia)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRBJugadorFumon)
                            .addComponent(jLJugadorFumon)
                            .addComponent(jLShrek)
                            .addComponent(jRBJugadorShrek)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTPFPassword)
                        .addComponent(jTFNickName)
                        .addComponent(jTFApellido)
                        .addComponent(jTFNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addComponent(jDCFechaNaci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLTituloRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApellido)
                    .addComponent(jTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDCFechaNaci, 0, 0, Short.MAX_VALUE)
                    .addComponent(jLFechaNaci))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNickName)
                    .addComponent(jTFNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPassword)
                    .addComponent(jTPFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLJugadorHomero, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLJugadorFumon)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBJugadorFumon))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLJugadorPlayera)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBJugadorPlayera))
                                    .addComponent(jRBJugadorHomero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLStewie)
                            .addComponent(jLShrek)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLAvatar)
                        .addGap(113, 113, 113)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBJugadorStewie)
                            .addComponent(jRBJugadorRubia))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBAtras)
                            .addComponent(jBGuardar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRBJugadorShrek)))
                .addGap(48, 48, 48))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-480)/2, (screenSize.height-792)/2, 480, 792);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jTPFPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPFPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPFPasswordActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        String nombre, apellido, cedula, nick,avatar, fecha ;
        avatar= "";
        Calendar prueba;
        prueba = Calendar.getInstance();
        prueba = jDCFechaNaci.getCalendar();
        int control;
       ClienteSocket cliente = new ClienteSocket();
    if ((jTFNombre.getText().equals("")) || (jTFApellido.getText().equals(""))  
                || (jTFNickName.getText().equals("")) || (jTPFPassword.getPassword().toString().equals("")))
        JOptionPane.showMessageDialog(this, "DEBE LLENAR TODOS LOS CAMPOS ");
    else
    {
          

           if (jRBJugadorHomero.isSelected())
            {
                avatar = "JugadorHomero.jpg";
                System.out.println("Avatar  "+avatar);

            }

            if (jRBJugadorPlayera.isSelected())
            {
                avatar = "JugadorPlayera.jpg";
                System.out.println("Avatar  "+avatar);

            }
            if (jRBJugadorFumon.isSelected())
            {
                avatar = "JugadorFumon.jpg";
                System.out.println("Avatar  "+avatar);

            }
            if (jRBJugadorRubia.isSelected())
            {
                avatar = "JugadorRubia.jpg";
                System.out.println("Avatar  "+avatar);

            }
            if (jRBJugadorStewie.isSelected())
            {
                avatar = "JugadorStewie.jpg";
                System.out.println("Avatar  "+avatar);

            }
            if (jRBJugadorShrek.isSelected())
            {
                avatar = "JugadorSherk.jpg";
                System.out.println("Avatar  "+avatar);

            }
        
      fecha= new SimpleDateFormat("dd/MM/yy").format(jDCFechaNaci.getDate());

      nombre = jTFNombre.getText();
      apellido = jTFApellido.getText();
      nick = jTFNickName.getText();
      cedula = jTPFPassword.getText();
      //avatar = jLAvatar.getName();
        System.out.println(cedula);
      String resultado = cliente.ejecutarPeticion("3:" + nick + ":" + cedula + ":" + nombre + ":" + apellido + ":" + fecha + ":" + avatar, "localhost", 7687);
        System.out.println(resultado);
        resultado += ":" + nombre + ":" + apellido + ":" + avatar;

        //en la sesion abierta se guarda el nick que tiene
        Cliente.logica.SesionAbierta.Nick_sesion = nick;
           this.setVisible(false);
            Ventana_Crear_Cargar_Partida verVentana = new Ventana_Crear_Cargar_Partida(resultado);
            verVentana.setVisible(true);
            //String fecha= String.format(DD, MM,AA);
            //Comunicacion.obtenerDatos(jTFNombre, jTFApellido, jTFCedula, jDCFechaNaci.getDateFormatString(), jTFNickName, jTPFPassword, jLAvatar);
            System.out.println(jDCFechaNaci.getDateFormatString()); // .getDate().toString());

        
      


    }
        /*
        if ( (jTPFPassword.getPassword() == jTPFConfirmaPassword.getPassword()))  // true
        {
            this.setVisible(false);
            Ventana_Crear_Cargar_Partida verVentana = new Ventana_Crear_Cargar_Partida();
            verVentana.setVisible(true);
            //String fecha= String.format(DD, MM,AA);
            Comunicacion.obtenerDatos(jTFNombre, jTFApellido, jTFCedula, jDCFechaNaci.getDateFormatString(), jTFNickName, jTPFPassword, jLAvatar);
            System.out.println(jDCFechaNaci.getDate().toString());
        }
       else
        {
            jTPFPassword.setText("");
            jTPFConfirmaPassword.setText("");
            this.setVisible(false);
            VentanaMensajePassword verVentana = new VentanaMensajePassword();
            verVentana.setVisible(true);
        }*/

       
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
       VentanaInicio verVentana = new VentanaInicio();
       verVentana.setVisible(true);

    }//GEN-LAST:event_jBAtrasActionPerformed

    private void jRBJugadorStewieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBJugadorStewieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBJugadorStewieActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBGuardar;
    private com.toedter.calendar.JDateChooser jDCFechaNaci;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLAvatar;
    private javax.swing.JLabel jLFechaNaci;
    private javax.swing.JLabel jLJugadorFumon;
    private javax.swing.JLabel jLJugadorHomero;
    private javax.swing.JLabel jLJugadorPlayera;
    private javax.swing.JLabel jLNickName;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPassword;
    private javax.swing.JLabel jLShrek;
    private javax.swing.JLabel jLStewie;
    private javax.swing.JLabel jLTituloRegistroUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRBJugadorFumon;
    private javax.swing.JRadioButton jRBJugadorHomero;
    private javax.swing.JRadioButton jRBJugadorPlayera;
    private javax.swing.JRadioButton jRBJugadorRubia;
    private javax.swing.JRadioButton jRBJugadorShrek;
    private javax.swing.JRadioButton jRBJugadorStewie;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFNickName;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JPasswordField jTPFPassword;
    // End of variables declaration//GEN-END:variables

}
