/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Crear_Cargar_Partida.java
 *
 * Created on 09-ago-2010, 12:39:14
 */

package Interface;

/**
 *
 * @author Blacky G
 */
public class Crear_Cargar_Partida extends javax.swing.JFrame {

    /** Creates new form Crear_Cargar_Partida */
    public Crear_Cargar_Partida() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jBCrearr_P = new javax.swing.JButton();
        jBCargar_P = new javax.swing.JButton();
        jBSalir_cuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBCrearr_P.setText("Crear Partida");
        jBCrearr_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearr_PActionPerformed(evt);
            }
        });
        jBCrearr_P.setBounds(113, 160, 180, 23);
        jLayeredPane1.add(jBCrearr_P, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBCargar_P.setText("Cargar Partida");
        jBCargar_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCargar_PActionPerformed(evt);
            }
        });
        jBCargar_P.setBounds(113, 220, 180, 23);
        jLayeredPane1.add(jBCargar_P, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBSalir_cuenta.setText("Cerrar Sesion");
        jBSalir_cuenta.setBounds(113, 280, 180, 23);
        jLayeredPane1.add(jBSalir_cuenta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-474)/2, (screenSize.height-526)/2, 474, 526);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCrearr_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearr_PActionPerformed
       
    }//GEN-LAST:event_jBCrearr_PActionPerformed

    private void jBCargar_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCargar_PActionPerformed
         //LO QUE HARA EL BOTON
        Cargar_Partida Ventana = new Cargar_Partida();
        Ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBCargar_PActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_Cargar_Partida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCargar_P;
    private javax.swing.JButton jBCrearr_P;
    private javax.swing.JButton jBSalir_cuenta;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables

}
